# --- Evaluation Configuration ---

# Model Configuration
model_id: "OpenGVLab/InternVL3-1B"

# Data paths
data_dir: "data/coco/val2017"
train_path: "data/multicoco_train.json" # This is required by the script but will not be used
val_path: "data/multicoco_val.json"

# Training Hyperparameters (not used in eval-only mode, but good to have)
lr: 1e-5
weight_decay: 0.05
batch_size_training: 1
num_epochs: 1

# --- Execution Flow ---
# Set to true to run only the evaluation loop
only_eval: true 