# Main configuration for the second stage (Coconut) training.

project: multicoco
name: aokvqa-coconut
save_path: checkpoints
model_id: OpenGVLab/InternVL3-1B
load_model_path: "checkpoints/stage_0/YOUR_COT_CHECKPOINT.pt" # IMPORTANT: Update this path

# Staging
cot: False
coconut: True
c_thought: 2
max_latent_stage: 3
epochs_per_stage: 1

# Data
data_dir: data/
train_path: data/aokvqa_train.json
val_path: data/aokvqa_validation.json

# Training
batch_size_training: 8
gradient_accumulation_steps: 2
lr: !!float 5e-5
weight_decay: 0.01
bf16: True
save_only_improve: False
reset_optimizer: True
seed: 42
debug: False
only_eval: False 