# Main configuration for the first stage (CoT) training.

project: multicoco
name: aokvqa-cot
save_path: checkpoints
model_id: OpenGVLab/InternVL3-1B
load_model_path: null

# Staging
cot: True
coconut: False
c_thought: 0
max_latent_stage: 0
epochs_per_stage: 1

# Data
data_dir: data/
train_path: data/aokvqa_train.json
val_path: data/aokvqa_validation.json

# Training
batch_size_training: 1
gradient_accumulation_steps: 2
lr: !!float 5e-5
weight_decay: 0.01 
bf16: True
save_only_improve: True
reset_optimizer: False
seed: 42
debug: False
only_eval: False 