# Main configuration for evaluating a trained Coconut model.

project: multicoco
name: aokvqa-coconut-eval
save_path: checkpoints
model_id: OpenGVLab/InternVL3-1B
load_model_path: "checkpoints/stage_3/YOUR_FINAL_COCONUT_CHECKPOINT.pt" # IMPORTANT: Update this path

# Staging
cot: False
coconut: True
c_thought: 2
max_latent_stage: 3 # Does not affect eval, but kept for consistency
epochs_per_stage: 1 # Does not affect eval

# Data
data_dir: data/
train_path: null # Not used in eval
val_path: data/aokvqa_test.json

# Training
batch_size_training: 8
gradient_accumulation_steps: 1 # Does not affect eval
lr: !!float 5e-5 # Does not affect eval
weight_decay: 0.01 # Does not affect eval
bf16: True
save_only_improve: False # Does not affect eval
reset_optimizer: True # Does not affect eval
seed: 42
debug: False
only_eval: True 